---
#PVC for BamBuddy
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bambuddy-pvc 
  namespace: default
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage:  15Gi

---
# PVC for Bambu Studio
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bambustudio-pvc
  namespace: default
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi