# This is a PersistentVolumeClaim for BambuBuddy.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bambuddy-pvc 
  namespace: default
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage:  15Gi

---

# Deployment for BambuBuddy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bambuddy-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bambuddy
  template:
    metadata:
      labels:
        app: bambuddy
    spec:
      containers:
        - name: bambuddy-ct
          image: maziggy/bambuddy:1.2.5.1
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          volumeMounts:
            - name: bambuddy-pvc           
              mountPath: /app/data       
      volumes:
        - name: bambuddy-pvc              
          persistentVolumeClaim:
            claimName: bambuddy-pvc

---
#LoadBalancer Service for BambuBuddy
apiVersion: v1
kind: Service
metadata:
  name: bambuddy-svc
  namespace: default
  annotations:
    metallb.io/loadBalancerIPs: 192.168.0.214
spec:
  type: LoadBalancer
  selector: 
    app: bambuddy
  ports:
    - port: 80
      targetPort: 8000
      name: http
      protocol: TCP