all:
  children:
    control_plane:
      hosts:
        k3s-cp-1:
          ansible_host: 192.168.0.42
        k3s-cp-2:
          ansible_host: 192.168.0.50
        k3s-cp-3:
          ansible_host: 192.168.0.135
    workers:
      hosts:
        k3s-worker-1:
          ansible_host: 192.168.0.123
        k3s-worker-2:
          ansible_host: 192.168.0.63
        k3s-worker-3:
          ansible_host: 192.168.0.171
        k3s-worker-4:
          ansible_host: 192.168.0.114
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /mnt/c/Users/Rylan/.ssh/id_ed25519
