# This is a PersistentVolumeClaim for JellyFin.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-pvc 
  namespace: default
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage:  200Gi

---

# Deployment for JellyFin
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: jellyfin-ct
          image: jellyfin/jellyfin:2026072708
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          volumeMounts:
            - name: jellyfin-pvc           
              mountPath: /app/data       
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      volumes:
        - name: jellyfin-pvc              
          persistentVolumeClaim:
            claimName: jellyfin-pvc

---
#LoadBalancer Service for JellyFin
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-svc
  namespace: default
  annotations:
    metallb.io/loadBalancerIPs: 192.168.0.215
spec:
  type: LoadBalancer
  selector: 
    app: jellyfin
  ports:
    - port: 80
      targetPort: 8096
      name: http
      protocol: TCP
    - port: 8920
      targetPort: 8920
      name: https
      protocol: TCP


---
#RateLimit Middleware for JellyFin
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: jellyfin-ratelimit
  namespace: default
spec:
  rateLimit:
    average: 100
    burst: 50
    period: 1m

---

#Ingress for JellyFin
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-jellyfin-ratelimit@kubernetescrd
spec:
  rules:
    - host: jellyfin.outrunjanko.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin-svc
                port:
                  number: 80
  tls:
    - hosts:
        - jellyfin.outrunjanko.com
      secretName: jellyfin-outrunjanko-tls


