apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: homeassistant-ct
          image: homeassistant/home-assistant:2026.8.0b1
          ports:
            - containerPort: 8123
              name: http
              protocol: TCP
          volumeMounts:
            - name: homeassistant-pvc           
              mountPath: /config     
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL  
              add:
                - NET_RAW
      volumes:
        - name: homeassistant-pvc              
          persistentVolumeClaim:
            claimName: homeassistant-pvc