apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-pvc 
  namespace: default
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi