apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-home
  namespace: adguard-home
spec:
  selector:
    matchLabels:
      app: adguard-home
  replicas: 1 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: adguard-home
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: adguard-home
        image: adguard/adguardhome
        args:
          - --work-dir
          - /adguard/data/work
          - --config 
          - /adguard/data/AdGuardHome.yaml
        ports:
        - containerPort: 3000
          name: web
          protocol: TCP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 80
          name: http-tcp
          protocol: TCP
        volumeMounts:
        - name: adguard-home-storage
          mountPath: /adguard/data
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
            add:
              - NET_BIND_SERVICE
      volumes:
        - name: adguard-home-storage
          persistentVolumeClaim:
            claimName: adguard-home-pvc