apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-home-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: k8s-apps
  nfs:
    path: /srv/nfs/k8s-apps/adguard
    server: 192.168.0.202