apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-home-pvc
  namespace: adguard-home
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: k8s-apps
  volumeName: adguard-home-pv
  resources:
    requests:
      storage: 5Gi