apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data-pvc
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client # matches your dynamic NFS provisioner
  resources:
    requests:
      storage: 20Gi